apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.allNamespaces -}} Cluster {{- end -}} Role
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  - update
