apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.allNamespaces -}} Cluster {{- end -}} RoleBinding
metadata:
  name: {{ template "fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.allNamespaces -}} Cluster {{- end -}} Role
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: gsm-sa
